### ISSUE TITLE
Accepts bad.@example.com as valid address

### ISSUE THREAD

**Issue by madsen** [pali/Email-Address-XS#2] opened 2018-05-04 14:50 UTC
Email::Address::XS 1.03 accepts an address with a period right before the @ sign.  As I read [RFC 5322](https://tools.ietf.org/html/rfc5322#section-3.4.1), the local-part cannot end with a period unless it is a quoted-string.

That is, I expect the following:
```
Email::Address::XS->parse('good@example.com')->is_valid; # true
Email::Address::XS->parse('bad.@example.com')->is_valid; # false
Email::Address::XS->parse('bad.address.@example.com')->is_valid; # false
Email::Address::XS->parse('"ok."@example.com')->is_valid; # true
```
but they all return true.

This is a problem when using Email::Address::XS to validate addresses that will be passed to Email::Sender, which still uses Email::Address.  Email::Address 1.908 does not accept ".@", so you can get a "no recipients" error from Email::Sender even though Email::Address::XS claims the address is valid.

**Comment by pali** [comment] 2018-05-09 20:22
Thanks for report. You are right that such addresses are invalid per RFCs. It is caused by dovecot parser which successfully parse these addresses. And I was told that reason is because some emails really contains such addresses in email headers. I would wait how upstream dovecot want to solve this problem and based on this I decide for proper fix in Email::Address::XS.

**Comment by pali** [comment] 2018-05-19 13:19
Now I committed some fixes for validation of email addresses into git master branch. Please test and let me know if there are still some problems.

**Comment by pali** [comment] 2018-06-09 16:42
New version 1.04 of Email::Address::XS with these changes were release to CPAN.

**Closed as completed by pali** 2018-06-09 16:42 UTC
